# Site settings
remote_theme: chesterhow/tale
title:          Lisbon Revsited
description:    "Cenas"

url:            "https://pablu.github.io/vortice"

# Author
author:
  name:         Ulises
  url:          https://pablu.github.io/lisbonrevisited
  email:        pablu@protonmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:title
paginate:       10
